(()=>{'use strict';
const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d'),W=1600,H=900;
const field={l:300,r:1367,t:145,b:788},goal={top:350,bottom:585,depth:58};
const ui={start:document.getElementById('startOverlay'),end:document.getElementById('endOverlay'),startBtn:document.getElementById('startBtn'),restartBtn:document.getElementById('restartBtn'),blue:document.getElementById('blueScore'),red:document.getElementById('redScore'),clock:document.getElementById('clock'),phase:document.getElementById('phaseLabel'),event:document.getElementById('eventBanner'),eventSmall:document.getElementById('eventSmall'),eventTitle:document.getElementById('eventTitle'),eventSub:document.getElementById('eventSub'),posBar:document.getElementById('possessionBar'),posText:document.getElementById('possessionText'),charge:document.getElementById('chargeMeter'),chargeFill:document.getElementById('chargeFill'),chargeValue:document.getElementById('chargeValue'),sound:document.getElementById('soundBtn'),fullscreen:document.getElementById('fullscreenBtn'),pause:document.getElementById('pauseOverlay'),resultTitle:document.getElementById('resultTitle'),resultMessage:document.getElementById('resultMessage'),resultIcon:document.getElementById('resultIcon'),finalResult:document.getElementById('finalResult'),shotsStat:document.getElementById('shotsStat'),possessionStat:document.getElementById('possessionStat'),passesStat:document.getElementById('passesStat'),joystick:document.getElementById('joystick'),nub:document.getElementById('joystickNub'),kick:document.getElementById('kickButton')};
const bg=new Image();bg.src='assets/arena.svg';
const C={blue:'#54efff',blueDark:'#08798c',red:'#ff4f67',redDark:'#8f1834',lime:'#c8ff2e',white:'#f6fbff'};
const S={phase:'menu',paused:false,blue:0,red:0,time:120,golden:false,kickoff:0,goalPause:0,last:performance.now(),acc:0,keys:{},pointer:{x:1100,y:450},players:[],ball:null,particles:[],trail:[],shake:0,flash:0,sound:true,audio:null,bluePoss:0,redPoss:0,stats:{shots:0,passes:0},touch:{x:0,y:0},charging:false,charge:0,eventTimer:0,mobile:matchMedia('(pointer:coarse)').matches};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}},fmt=n=>{const total=Math.max(0,Math.ceil(n));return String(Math.floor(total/60)).padStart(2,'0')+':'+String(total%60).padStart(2,'0')};
const installBtn=document.getElementById('installBtn');let installPrompt=null;
addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(installBtn)installBtn.hidden=false});
installBtn?.addEventListener('click',async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;installBtn.hidden=true});
addEventListener('appinstalled',()=>{installPrompt=null;if(installBtn)installBtn.hidden=true});
if('serviceWorker'in navigator&&/^https?:$/.test(location.protocol))addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
function audio(){if(S.audio)return;const A=window.AudioContext||window.webkitAudioContext;if(A)S.audio=new A()}
function tone(f,d=.15,type='sine',v=.05,delay=0,slide=0){if(!S.sound||!S.audio)return;const a=S.audio,t=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,f+slide),t+d);g.gain.setValueAtTime(.0001,t);g.gain.linearRampToValueAtTime(v,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(a.destination);o.start(t);o.stop(t+d+.02)}
function noise(d=.2,v=.08,delay=0){if(!S.sound||!S.audio)return;const a=S.audio,n=Math.floor(a.sampleRate*d),b=a.createBuffer(1,n,a.sampleRate),q=b.getChannelData(0);for(let i=0;i<n;i++)q[i]=(Math.random()*2-1)*Math.pow(1-i/n,1.5);const s=a.createBufferSource(),f=a.createBiquadFilter(),g=a.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=1200;g.gain.value=v;s.connect(f).connect(g).connect(a.destination);s.start(a.currentTime+delay)}
function sfx(n){if(n==='kick'){tone(90,.14,'sine',.12,0,-35);noise(.09,.08)}if(n==='hit')tone(180,.08,'square',.022,0,-55);if(n==='whistle'){tone(1800,.13,'sine',.04);tone(2250,.1,'sine',.03,.08,-300)}if(n==='goal'){noise(.8,.08);[330,440,554,660].forEach((f,i)=>tone(f,.55,'sawtooth',.022,i*.06,80))}if(n==='end'){tone(1500,.16,'sine',.04);tone(1250,.18,'sine',.035,.18);tone(950,.2,'sine',.03,.38)}}
function player(team,x,y,name,user=false,role='support'){return{team,x,y,vx:0,vy:0,r:29,name,user,role,facing:{x:team==='blue'?1:-1,y:0},cool:0,think:0,target:{x,y},energy:100,glow:0,touch:0}}
function setup(){S.blue=0;S.red=0;S.time=120;S.golden=false;S.stats={shots:0,passes:0};S.bluePoss=0;S.redPoss=0;S.particles=[];S.trail=[];S.players=[player('blue',610,466,'TU',true,'captain'),player('blue',485,330,'NEX',false,'defender'),player('blue',540,610,'LIO',false,'support'),player('red',1050,466,'REX',false,'striker'),player('red',1190,330,'KAI',false,'defender'),player('red',1135,610,'ZED',false,'support')];S.ball={x:834,y:466,vx:0,vy:0,r:16,lastTeam:null,lastPlayer:null,spin:0,trapTime:0,antiTrap:0,kickGrace:0};S.phase='playing';S.paused=false;resetKickoff();updateUI()}
function resetKickoff(scoredBy=null){const p=S.players,spots=[[610,466],[485,330],[540,610],[1050,466],[1190,330],[1135,610]];p.forEach((a,i)=>{a.x=spots[i][0];a.y=spots[i][1];a.vx=a.vy=0;a.cool=0});S.ball.x=834;S.ball.y=466;S.ball.vx=S.ball.vy=0;S.ball.lastTeam=null;S.ball.trapTime=0;S.ball.antiTrap=0;S.ball.kickGrace=0;S.kickoff=1.7;S.goalPause=0;showEvent(scoredBy?`${scoredBy==='blue'?'NEON FC':'VORTEX'} MARCA`:'KICK OFF',scoredBy?'A ARENA EXPLODE':'DOMINA O CAMPO',scoredBy==='red'?'red':'',1.4)}
function showEvent(title,sub,cls='',time=1.2,small='FUTDATA ARENA'){ui.eventSmall.textContent=small;ui.eventTitle.textContent=title;ui.eventSub.textContent=sub;ui.event.className='event-banner show '+cls;S.eventTimer=time}
function updateUI(){ui.blue.textContent=S.blue;ui.red.textContent=S.red;ui.clock.textContent=S.golden?'GOLD':fmt(S.time);ui.phase.textContent=S.golden?'GOLO DE OURO':'JOGO';const tot=S.bluePoss+S.redPoss||1,b=Math.round(S.bluePoss/tot*100),r=100-b;ui.posBar.style.width=b+'%';ui.posText.textContent=`${b} / ${r}`}
function begin(){audio();S.audio?.resume();ui.start.classList.add('hidden');ui.end.classList.add('hidden');setup();if(S.mobile){Promise.resolve(document.getElementById('game').requestFullscreen?.()).catch(()=>{});Promise.resolve(screen.orientation?.lock?.('landscape')).catch(()=>{})}setTimeout(()=>sfx('whistle'),180)}
ui.startBtn.onclick=begin;ui.restartBtn.onclick=()=>{ui.end.classList.add('hidden');setup();setTimeout(()=>sfx('whistle'),180)};ui.sound.onclick=()=>{S.sound=!S.sound;ui.sound.style.opacity=S.sound?1:.35;if(S.sound){audio();tone(650,.1)}};ui.fullscreen.onclick=()=>document.fullscreenElement?document.exitFullscreen?.():document.getElementById('game').requestFullscreen?.();
addEventListener('keydown',e=>{S.keys[e.code]=true;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Space'&&!e.repeat&&S.phase==='playing')startCharge();if(e.code==='KeyP'&&S.phase==='playing')togglePause()});addEventListener('keyup',e=>{S.keys[e.code]=false;if(e.code==='Space')releaseCharge()});
addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('visibilitychange',()=>{if(document.hidden&&S.phase==='playing'&&!S.paused)togglePause()});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();S.pointer.x=(e.clientX-r.left)/r.width*W;S.pointer.y=(e.clientY-r.top)/r.height*H});canvas.addEventListener('pointerdown',e=>{if(e.button===0&&S.phase==='playing')startCharge()});canvas.addEventListener('pointerup',e=>{if(e.button===0)releaseCharge()});
function togglePause(){S.paused=!S.paused;ui.pause.classList.toggle('hidden',!S.paused)}function startCharge(){if(S.paused||S.kickoff>0)return;S.charging=true;S.charge=Math.max(S.charge,.08);ui.charge.classList.add('active')}function releaseCharge(){if(!S.charging)return;userKick();S.charging=false;S.charge=0;ui.charge.classList.remove('active');ui.chargeFill.style.width='0%'}
let joyId=null;ui.joystick.addEventListener('pointerdown',e=>{joyId=e.pointerId;ui.joystick.setPointerCapture(e.pointerId)});ui.joystick.addEventListener('pointermove',e=>{if(e.pointerId!==joyId)return;const r=ui.joystick.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2),d=Math.hypot(x,y),limit=r.width*.32,m=Math.min(limit,d),n=norm(x,y);S.touch.x=n.x*Math.min(1,d/limit);S.touch.y=n.y*Math.min(1,d/limit);ui.nub.style.transform=`translate(${n.x*m}px,${n.y*m}px)`});const joyEnd=()=>{joyId=null;S.touch.x=S.touch.y=0;ui.nub.style.transform='none'};ui.joystick.addEventListener('pointerup',joyEnd);ui.joystick.addEventListener('pointercancel',joyEnd);ui.kick.addEventListener('pointerdown',startCharge);ui.kick.addEventListener('pointerup',releaseCharge);ui.kick.addEventListener('pointercancel',releaseCharge);
function userKick(){const u=S.players[0],b=S.ball,d=dist(u,b);if(d>u.r+b.r+18||u.cool>0){tone(130,.06,'sine',.02);return}let aim=S.mobile?norm(b.x-u.x,b.y-u.y):norm(S.pointer.x-u.x,S.pointer.y-u.y);if(!isFinite(aim.x)||Math.hypot(aim.x,aim.y)<.1)aim=u.facing;const power=520+S.charge*420;b.vx=aim.x*power+u.vx*.35;b.vy=aim.y*power+u.vy*.35;b.lastTeam='blue';b.lastPlayer=u;armKickRelease(b);u.cool=.28;u.glow=1;S.stats.shots+=(aim.x>.35&&u.x>800)?1:0;burst(b.x,b.y,18,C.lime);S.shake=7;if(S.mobile)navigator.vibrate?.(18);sfx('kick')}
function botKick(p){const b=S.ball;if(p.cool>0||dist(p,b)>p.r+b.r+15)return;const dir=p.team==='blue'?1:-1,goalX=p.team==='blue'?field.r+40:field.l-40,wallBall=b.y<field.t+100||b.y>field.b-100||((b.x<field.l+100||b.x>field.r-100)&&!(b.y>goal.top&&b.y<goal.bottom));let target=wallBall?{x:834+(Math.random()-.5)*130,y:466+(Math.random()-.5)*100}:{x:goalX,y:clamp(b.y+(Math.random()-.5)*150,goal.top+22,goal.bottom-22)};const mates=S.players.filter(x=>x.team===p.team&&x!==p);const ahead=mates.filter(m=>(m.x-p.x)*dir>70&&dist(m,p)<330);if(!wallBall&&ahead.length&&Math.random()<.24){const m=ahead[Math.floor(Math.random()*ahead.length)];target={x:m.x+dir*28,y:m.y};S.stats.passes+=p.team==='blue'?1:0}const a=Math.atan2(target.y-b.y,target.x-b.x)+(Math.random()-.5)*.16,n={x:Math.cos(a),y:Math.sin(a)},pow=wallBall?750:590+Math.random()*175;b.vx=n.x*pow+p.vx*.25;b.vy=n.y*pow+p.vy*.25;b.lastTeam=p.team;b.lastPlayer=p;armKickRelease(b);p.cool=.5+Math.random()*.22;p.glow=1;if(Math.abs(n.x)>.6&&((p.team==='blue'&&p.x>850)||(p.team==='red'&&p.x<750)))S.stats.shots+=p.team==='blue'?1:0;burst(b.x,b.y,12,p.team==='blue'?C.cyan:C.red);S.shake=4;sfx('kick')}
function armKickRelease(b){const crowd=S.players.filter(p=>dist(p,b)<p.r+b.r+45).length,nearWall=b.y<field.t+95||b.y>field.b-95||b.x<field.l+95||b.x>field.r-95;b.kickGrace=nearWall&&crowd>=2?.16:.055}
function ai(p,dt){p.think-=dt;if(p.think>0)return;p.think=.08+Math.random()*.07;const team=S.players.filter(x=>x.team===p.team),bots=team.filter(x=>!x.user),b=S.ball,dir=p.team==='blue'?1:-1,ownX=p.team==='blue'?field.l:field.r;const eligible=team.filter(x=>!x.user||dist(x,b)>190),chaser=eligible.reduce((a,x)=>dist(x,b)<dist(a,b)?x:a,eligible[0]);let tx,ty;if(p===chaser){const lead=.20;tx=b.x+b.vx*lead;ty=b.y+b.vy*lead;if(dist(p,b)<p.r+b.r+18)botKick(p)}else if(p.role==='defender'){tx=ownX+dir*105;ty=clamp(b.y,goal.top+45,goal.bottom-45);if((b.x-ownX)*dir<250){tx=b.x-dir*45;ty=b.y}}else{tx=clamp(b.x-dir*190,field.l+120,field.r-120);ty=clamp(b.y+(p.name.charCodeAt(0)%2?145:-145),field.t+80,field.b-80)}p.target.x=tx+(Math.random()-.5)*15;p.target.y=ty+(Math.random()-.5)*15}
function step(dt){if(S.paused||S.phase!=='playing')return;if(S.eventTimer>0){S.eventTimer-=dt;if(S.eventTimer<=0)ui.event.className='event-banner'}if(S.goalPause>0){S.goalPause-=dt;if(S.goalPause<=0)resetKickoff(S.lastGoal);return}if(S.kickoff>0){S.kickoff-=dt;if(S.kickoff<=0){ui.event.className='event-banner';sfx('whistle')}return}if(!S.golden){S.time-=dt;if(S.time<=0){S.time=0;if(S.blue===S.red){S.golden=true;showEvent('GOLO DE OURO','QUEM MARCAR VENCE','',2,'EMPATE')}else finish();updateUI();return}}
const u=S.players[0];let mx=(S.keys.KeyD||S.keys.ArrowRight?1:0)-(S.keys.KeyA||S.keys.ArrowLeft?1:0)+S.touch.x,my=(S.keys.KeyS||S.keys.ArrowDown?1:0)-(S.keys.KeyW||S.keys.ArrowUp?1:0)+S.touch.y;let n=norm(mx,my);if(!mx&&!my)n={x:0,y:0};const sprint=(S.keys.ShiftLeft||S.keys.ShiftRight)&&u.energy>0,max=sprint?385:315,acc=sprint?980:830;u.vx+=n.x*acc*dt;u.vy+=n.y*acc*dt;const sp=Math.hypot(u.vx,u.vy);if(sp>max){u.vx=u.vx/sp*max;u.vy=u.vy/sp*max}if(mx||my)u.facing=n;else{const a=norm(S.pointer.x-u.x,S.pointer.y-u.y);u.facing=a}u.energy=clamp(u.energy+(sprint?-34:18)*dt,0,100);if(S.charging){S.charge=clamp(S.charge+dt*1.35,0,1);ui.chargeFill.style.width=(S.charge*100)+'%';ui.chargeValue.textContent=Math.round(S.charge*100)+'%'}
for(const p of S.players){if(!p.user){ai(p,dt);const d=norm(p.target.x-p.x,p.target.y-p.y);p.vx+=d.x*675*dt;p.vy+=d.y*675*dt;const m=Math.hypot(p.vx,p.vy),lim=275;if(m>lim){p.vx=p.vx/m*lim;p.vy=p.vy/m*lim}if(m>20)p.facing={x:p.vx/m,y:p.vy/m}}p.cool=Math.max(0,p.cool-dt);p.glow=Math.max(0,p.glow-dt*3);p.vx*=Math.exp(-3.25*dt);p.vy*=Math.exp(-3.25*dt);p.x+=p.vx*dt;p.y+=p.vy*dt;walls(p)}
for(let i=0;i<S.players.length;i++)for(let j=i+1;j<S.players.length;j++)collide(S.players[i],S.players[j],.35);const b=S.ball;b.kickGrace=Math.max(0,b.kickGrace-dt);for(const p of S.players)collidePlayerBall(p,b);b.vx*=Math.exp(-.62*dt);b.vy*=Math.exp(-.62*dt);b.x+=b.vx*dt;b.y+=b.vy*dt;b.spin+=Math.hypot(b.vx,b.vy)*dt*.018;ballWalls();deadlockProtection(dt);const speed=Math.hypot(b.vx,b.vy);if(speed>90){S.trail.push({x:b.x,y:b.y,a:.32,r:b.r});if(S.trail.length>14)S.trail.shift()}else if(S.trail.length)S.trail.shift();if(b.lastTeam==='blue')S.bluePoss+=dt;else if(b.lastTeam==='red')S.redPoss+=dt;updateParticles(dt);updateUI()}
function walls(p){p.x=clamp(p.x,field.l+p.r,field.r-p.r);p.y=clamp(p.y,field.t+p.r,field.b-p.r)}
function collide(a,b,re=.45){let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=a.r+b.r;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,over=min-d;a.x-=nx*over*.5;a.y-=ny*over*.5;b.x+=nx*over*.5;b.y+=ny*over*.5;const rv=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rv<0){const imp=-(1+re)*rv/2;a.vx-=imp*nx;a.vy-=imp*ny;b.vx+=imp*nx;b.vy+=imp*ny}}
function collidePlayerBall(p,b){if(b.kickGrace>0)return;let dx=b.x-p.x,dy=b.y-p.y,d=Math.hypot(dx,dy),min=p.r+b.r;if(d>=min||d===0)return;const nx=dx/d,ny=dy/d,over=min-d;b.x+=nx*over;b.y+=ny*over;const rv=(b.vx-p.vx)*nx+(b.vy-p.vy)*ny;if(rv<0){const imp=-(1+.58)*rv/1.45;b.vx+=imp*nx+p.vx*.18;b.vy+=imp*ny+p.vy*.18}b.lastTeam=p.team;b.lastPlayer=p;p.touch=.12;if(Math.abs(rv)>130){burst(b.x,b.y,5,p.team==='blue'?C.cyan:C.red);sfx('hit')}}
function ballWalls(){const b=S.ball,inMouth=b.y>goal.top+b.r*.15&&b.y<goal.bottom-b.r*.15;if(b.y-b.r<field.t){b.y=field.t+b.r;b.vy=Math.abs(b.vy)*.82;wallHit(b)}if(b.y+b.r>field.b){b.y=field.b-b.r;b.vy=-Math.abs(b.vy)*.82;wallHit(b)}if(!inMouth){if(b.x-b.r<field.l){b.x=field.l+b.r;b.vx=Math.abs(b.vx)*.82;wallHit(b)}if(b.x+b.r>field.r){b.x=field.r-b.r;b.vx=-Math.abs(b.vx)*.82;wallHit(b)}}else{if(b.x<field.l-goal.depth*.75)goalScored('red');if(b.x>field.r+goal.depth*.75)goalScored('blue')}}
function deadlockProtection(dt){const b=S.ball;b.antiTrap=Math.max(0,b.antiTrap-dt);const inMouth=b.y>goal.top&&b.y<goal.bottom,walls=[{d:b.y-(field.t+b.r),x:0,y:1},{d:(field.b-b.r)-b.y,x:0,y:-1}];if(!inMouth){walls.push({d:b.x-(field.l+b.r),x:1,y:0},{d:(field.r-b.r)-b.x,x:-1,y:0})}walls.sort((a,c)=>a.d-c.d);const wall=walls[0],crowd=S.players.filter(p=>dist(p,b)<p.r+b.r+48).length,pinned=wall.d<72&&crowd>=2,scrum=crowd>=3&&Math.hypot(b.vx,b.vy)<95;if(pinned||scrum)b.trapTime+=dt;else b.trapTime=Math.max(0,b.trapTime-dt*3);const limit=pinned?.30:.72;if(b.trapTime<limit||b.antiTrap>0)return;const inward=pinned?{x:wall.x,y:wall.y}:norm(834-b.x,466-b.y),side={x:-inward.y,y:inward.x},swerve=(Math.random()-.5)*190;b.x=clamp(b.x+inward.x*38,field.l+b.r+6,field.r-b.r-6);b.y=clamp(b.y+inward.y*38,field.t+b.r+6,field.b-b.r-6);b.vx=inward.x*760+side.x*swerve;b.vy=inward.y*760+side.y*swerve;b.kickGrace=.19;for(const p of S.players){if(dist(p,b)<p.r+b.r+75){const away=norm(p.x-b.x,p.y-b.y);p.vx+=away.x*185;p.vy+=away.y*185}}b.trapTime=0;b.antiTrap=1.05;burst(b.x,b.y,22,C.lime);S.shake=Math.max(S.shake,7);sfx('kick')}
function wallHit(b){S.shake=Math.min(7,S.shake+2);burst(b.x,b.y,6,'#d8fbff');tone(230,.06,'square',.018)}
function goalScored(team){if(S.goalPause>0)return;team==='blue'?S.blue++:S.red++;S.lastGoal=team;S.goalPause=2.25;S.shake=18;S.flash=.85;burst(S.ball.x,S.ball.y,110,team==='blue'?C.cyan:C.red);showEvent('GOLO!',team==='blue'?'NEON FC EM VANTAGEM':'VORTEX RESPONDE',team==='red'?'red':'',2,'A ARENA EXPLODE');if(S.mobile)navigator.vibrate?.([45,35,90]);sfx('goal');updateUI();if(S.golden)setTimeout(finish,1300)}
function finish(){if(S.phase!=='playing')return;S.phase='ended';sfx('end');const win=S.blue>S.red,draw=S.blue===S.red;ui.resultIcon.textContent=win?'W':draw?'D':'L';ui.resultIcon.style.color=win?C.lime:draw?C.cyan:C.red;ui.resultTitle.textContent=win?'VITÓRIA!':draw?'EMPATE':'DERROTA';ui.resultMessage.textContent=win?'Controlaste o ritmo e conquistaste a arena.':draw?'Duas equipas separadas por nada.':'A arena exige uma desforra.';ui.finalResult.textContent=`${S.blue} — ${S.red}`;ui.shotsStat.textContent=S.stats.shots;const tot=S.bluePoss+S.redPoss||1;ui.possessionStat.textContent=Math.round(S.bluePoss/tot*100)+'%';ui.passesStat.textContent=S.stats.passes;setTimeout(()=>ui.end.classList.remove('hidden'),500)}
function burst(x,y,n,color){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*270;S.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.35+Math.random()*.7,max:1.05,size:1+Math.random()*4,color})}}
function updateParticles(dt){for(let i=S.particles.length-1;i>=0;i--){const p=S.particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-1.8*dt);p.vy*=Math.exp(-1.8*dt);if(p.life<=0)S.particles.splice(i,1)}S.shake*=Math.pow(.04,dt);S.flash=Math.max(0,S.flash-dt*1.8)}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*S.shake,(Math.random()-.5)*S.shake);if(bg.complete)ctx.drawImage(bg,0,0,W,H);else{ctx.fillStyle='#0b2c21';ctx.fillRect(0,0,W,H)}drawPitch();drawGoals();for(const t of S.trail){ctx.globalAlpha=t.a;ctx.fillStyle='#e9ffff';ctx.beginPath();ctx.arc(t.x,t.y,t.r*.75,0,Math.PI*2);ctx.fill();t.a*=.88}ctx.globalAlpha=1;const ordered=[...S.players].sort((a,b)=>a.y-b.y);for(const p of ordered)drawPlayer(p);if(S.ball)drawBall();drawParticles();drawLight();if(S.flash){ctx.fillStyle=`rgba(230,255,255,${S.flash*.26})`;ctx.fillRect(0,0,W,H)}ctx.restore()}
function drawPitch(){ctx.save();ctx.strokeStyle='rgba(232,255,250,.78)';ctx.lineWidth=3;ctx.shadowColor='rgba(84,239,255,.28)';ctx.shadowBlur=7;ctx.strokeRect(field.l,field.t,field.r-field.l,field.b-field.t);ctx.beginPath();ctx.moveTo(834,field.t);ctx.lineTo(834,field.b);ctx.stroke();ctx.beginPath();ctx.arc(834,466,103,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(834,466,4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeRect(field.l,goal.top-52,150,(goal.bottom-goal.top)+104);ctx.strokeRect(field.r-150,goal.top-52,150,(goal.bottom-goal.top)+104);ctx.beginPath();ctx.arc(field.l+115,466,70,-Math.PI/2,Math.PI/2);ctx.stroke();ctx.beginPath();ctx.arc(field.r-115,466,70,Math.PI/2,Math.PI*1.5);ctx.stroke();ctx.restore()}
function drawGoals(){ctx.save();for(const side of ['left','right']){const x=side==='left'?field.l:field.r,d=side==='left'?-goal.depth:goal.depth;ctx.fillStyle='rgba(210,250,255,.08)';ctx.fillRect(Math.min(x,x+d),goal.top,Math.abs(d),goal.bottom-goal.top);ctx.strokeStyle='rgba(225,252,255,.85)';ctx.lineWidth=5;ctx.shadowColor=C.cyan;ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(x,goal.top);ctx.lineTo(x+d,goal.top);ctx.lineTo(x+d,goal.bottom);ctx.lineTo(x,goal.bottom);ctx.stroke();ctx.lineWidth=1;ctx.shadowBlur=0;for(let i=1;i<5;i++){const xx=lerp(x,x+d,i/5);ctx.beginPath();ctx.moveTo(xx,goal.top);ctx.lineTo(xx,goal.bottom);ctx.stroke()}for(let i=1;i<7;i++){const y=lerp(goal.top,goal.bottom,i/7);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+d,y);ctx.stroke()}}ctx.restore()}
function drawPlayer(p){ctx.save();ctx.translate(p.x,p.y);const team=p.team==='blue',color=team?C.blue:C.red,dark=team?C.blueDark:C.redDark;ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(5,12,p.r*1.08,p.r*.56,0,0,Math.PI*2);ctx.fill();if(p.glow){ctx.shadowColor=color;ctx.shadowBlur=32*p.glow}const g=ctx.createRadialGradient(-10,-12,3,0,0,p.r);g.addColorStop(0,'#fff');g.addColorStop(.08,color);g.addColorStop(.62,dark);g.addColorStop(1,'#031117');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=p.user?C.lime:'rgba(255,255,255,.62)';ctx.lineWidth=p.user?4:2;ctx.stroke();ctx.rotate(Math.atan2(p.facing.y,p.facing.x));ctx.fillStyle='rgba(255,255,255,.9)';ctx.beginPath();ctx.moveTo(p.r-5,0);ctx.lineTo(p.r-15,-7);ctx.lineTo(p.r-15,7);ctx.closePath();ctx.fill();ctx.rotate(-Math.atan2(p.facing.y,p.facing.x));ctx.fillStyle='#f8fdff';ctx.font=`900 ${p.user?14:12}px Arial`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(p.user?'7':p.name.charCodeAt(0)%9+1,0,1);if(p.user){ctx.strokeStyle='rgba(200,255,46,.25)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,p.r+8,-Math.PI/2,-Math.PI/2+Math.PI*2*(p.energy/100));ctx.stroke();ctx.fillStyle=C.lime;ctx.beginPath();ctx.moveTo(0,-p.r-22);ctx.lineTo(-7,-p.r-33);ctx.lineTo(7,-p.r-33);ctx.closePath();ctx.fill()}ctx.fillStyle='rgba(2,8,12,.78)';ctx.fillRect(-24,-p.r-18,48,13);ctx.fillStyle=p.user?C.lime:'#fff';ctx.font='800 9px Arial';ctx.fillText(p.name,0,-p.r-11);ctx.restore()}
function drawBall(){const b=S.ball;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.spin);ctx.fillStyle='rgba(0,0,0,.42)';ctx.beginPath();ctx.ellipse(4,9,b.r*1.15,b.r*.7,0,0,Math.PI*2);ctx.fill();const g=ctx.createRadialGradient(-6,-7,2,0,0,b.r);g.addColorStop(0,'#fff');g.addColorStop(.58,'#e6eef0');g.addColorStop(1,'#65727a');ctx.fillStyle=g;ctx.shadowColor='rgba(210,255,255,.55)';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#07131a';ctx.beginPath();for(let i=0;i<5;i++){const a=-Math.PI/2+i*Math.PI*2/5;i?ctx.lineTo(Math.cos(a)*6,Math.sin(a)*6):ctx.moveTo(Math.cos(a)*6,Math.sin(a)*6)}ctx.closePath();ctx.fill();ctx.strokeStyle='#26343b';ctx.lineWidth=2;for(let i=0;i<5;i++){ctx.rotate(Math.PI*2/5);ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(0,-b.r+2);ctx.stroke()}ctx.restore()}
function drawParticles(){ctx.save();ctx.globalCompositeOperation='screen';for(const p of S.particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.globalAlpha=1}
function drawLight(){const g=ctx.createRadialGradient(834,466,180,834,466,820);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.72,'rgba(0,0,0,.02)');g.addColorStop(1,'rgba(0,2,5,.38)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function loop(now){const dt=Math.min(.04,(now-S.last)/1000||0);S.last=now;S.acc+=dt;while(S.acc>=1/120){step(1/120);S.acc-=1/120}draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
